### PR TITLE
fix: Test hooks timeout when using rest transport

### LINKED ISSUE #250: Test hooks timeout when using rest transport
* **Node.js version**: v12.16.1
* **itoolkit version**: 1.0.0-alpha.1 (latest master)
* **IBM i version**: 7.2
* **XMLSERVICE version**: XML Toolkit 2.0.2-dev

**Describe the bug**

When running functional tests using rest transport the the check object exists before hook times out. This occurs because the callback is not invoked when the rest transport is used see [checkObjectExists.js](https://github.com/IBM/nodejs-itoolkit/blob/master/test/functional/checkObjectExists.js#L172). 

We need to simply bail out and invoke the callback when the rest transport is used because the rest transport cannot check that an object exists.

```
  1) DataQueue Functional Tests
       "before all" hook: check if data queue exists for tests in "DataQueue Functional Tests":
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

  2) iWork Functional Tests
       getDataArea
         "before all" hook: check if data area exists for tests for "returns contents of a data area":
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

```

### PR DESCRIPTION
**Pull request by abmusse**
Fixes #250

### CODE REVIEW

File: test/functional/checkObjectExists.js [hunk 1]
```diff
@@ -169,6 +169,8 @@ function checkObjectExists(config, name, type, callback) {
     checkObjectExistsODBC(config.transportOptions, object, callback);
   } else if (config.transport === 'ssh') {
     checkObjectExistsSSH(config.transportOptions, object, callback);
+  } else { // we cannot check object existence using the rest transport
+    callback(null);
```
Comment (kadler) [inline test/functional/checkObjectExists.js:173]:
```suggestion
    callback(null, true);
```

Shouldn't we pass the second parameter? Otherwise the check will get an undefined which would prevent it from running.

Comment (abmusse) [reply test/functional/checkObjectExists.js]: Thats right, I will fix this up.

File: test/functional/checkObjectExists.js [hunk 2]
```diff
@@ -169,6 +169,8 @@ function checkObjectExists(config, name, type, callback) {
     checkObjectExistsODBC(config.transportOptions, object, callback);
   } else if (config.transport === 'ssh') {
     checkObjectExistsSSH(config.transportOptions, object, callback);
+  } else { // we cannot check object existence using the rest transport
```
Comment (kadler) [inline test/functional/checkObjectExists.js:172]: This code style looks very strange to me. Is this preferred by the eslint setup?

Comment (abmusse) [reply test/functional/checkObjectExists.js:172]: Yes if we do not have the else leg on the same line as the closing brace the `brace-style` error is shown see https://eslint.org/docs/rules/brace-style

Comment (abmusse) [reply test/functional/checkObjectExists.js:172]: I also found this weird at first. We can always disable this rule if we want though.

Comment (kadler) [reply test/functional/checkObjectExists.js:172]: Sorry, I was not referring to the else itself, but the comment on that line instead of on the next line.

Comment (abmusse) [reply test/functional/checkObjectExists.js:172]: Oh no that is not a linter issue I will move the comment down a line.

Comment (kadler) [reply test/functional/checkObjectExists.js:172]: As far as bracing styles go, I used to be an adherent to Allman styling, but now I prefer Stroustrup, but I'd probably leave it as-is since that's what the rest of the code uses already.
