### PR TITLE
fix: ssh transport silent failure

### LINKED ISSUE #224: SSH transport silently fails when hostname is invalid
**Node.js version**: v12.16.1
 **itoolkit version**: 1.0.0-alpha.1 (latest master)
 **IBM i version**: 7.2
 **XMLSERVICE version**: XML Toolkit 2.0.2-dev

**Describe the bug**

Using the ssh transport with invalid hostname silently fails. This problem is masked until you turn on verbose mode with `Connection.debug(true)`. Otherwise the error or xmlOutput is not passed to  `done` callback.

within [sshTransport.js](https://github.com/IBM/nodejs-itoolkit/blob/master/lib/transports/sshTransport.js#L32):

```
  client.on('error', (error) => {
    if (verbose) {
      console.log('SSH CLIENT ERROR: ', error);
    }
    ERROR = error;
    client.end();
  });

  client.on('end', () => {
    if (verbose) {
      console.log('SSH Client has ended');
    }

    if (ERROR) {
      done(ERROR, null);
      return;
    }

    done(null, xmlOut);
  });

```

Currently we handle error events by setting `ERROR` variable and calling `client.end()`.

We have a handler for `end` event where we actually call our done callback.

The issue here is that `end` event never fires because the client is not even connect at this point.

**To Reproduce**
```js
const {
  Connection, CommandCall,
} = require('./lib/itoolkit');

const { parseString } = require('xml2js');

const conn = new Connection({
  transport: 'ssh',
  transportOptions: { host: process.env.TKHOST, username: process.env.TKUSER, password: process.env.TKPASS }
});

conn.debug(true);
conn.add(new CommandCall({ command: 'RTVJOBA USRLIBL(?) SYSLIBL(?)', type: 'cl' }));

conn.run((error, xmlOutput) => {
  if (error) {
    throw error;
  }
  parseString(xmlOutput, (parseError, result) => {
    if (parseError) {
      throw parseError;
    }
    console.log(JSON.stringify(result));
  });
});

```

```
============
INPUT XML
============
<?xml version='1.0'?><myscript><cmd exec='rexx' error='fast'>RTVJOBA USRLIBL(?) SYSLIBL(?)</cmd></myscript>
SSH CLIENT ERROR:  Error: getaddrinfo ENOTFOUND myhost
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'myhost',
  level: 'client-socket'
}
SSH Client has closed

```

We should handle the call the done callback with the error within the `error` event handler rather than in `end` event handler.

We should move calls to `client.end()` within the `client.exec` callback when we detect an error has occured.

### PR DESCRIPTION
**Pull request by abmusse**
Fixes #224

### CODE REVIEW

File: lib/transports/sshTransport.js [hunk 1]
```diff
@@ -65,6 +56,7 @@ function sshCall(config, xmlIn, done) {
         if (verbose) {
           console.log('Exec error: ', error);
         }
+        client.end();
```
Comment (kadler) [inline lib/transports/sshTransport.js:59]: Looks like `client.end()` will check that it's [connected](https://github.com/mscdex/ssh2/blob/master/lib/client.js#L704) first, so we can move these calls in the error cases to the error handler itself and it will do the right thing regardless of if it is connected or not.

Comment (abmusse) [reply lib/transports/sshTransport.js:59]: Ok will move `client.end()` calls to the error handler.
