### PR TITLE
fix: HTTP transport should take a URL

### LINKED ISSUE #247: HTTP Transport should take a URL
Currently, the HTTP transport takes separate host, port, and path fields. This should just be simplified to a URL.

### PR DESCRIPTION
**Pull request by abmusse**
Fixes #247

### CODE REVIEW

File: lib/transports/httpTransport.js [hunk 1]
```diff
@@ -45,6 +43,11 @@ const httpCall = (config, xmlInput, done) => {
     return;
   }
 
+  if (!url || typeof password !== 'string') {
```
Comment (kadler) [inline lib/transports/httpTransport.js:46]: The password check should have its own error message

File: lib/Deprecated.js [hunk 2]
```diff
@@ -564,8 +564,9 @@ class iConn {
       // pre v1.0 falls back to idb transport when host is not specified
       if (option.host) {
         options.transport = 'rest';
+        // construct the url host:port/path
+        options.transportOptions.url = `http://${option.host}:${option.port || 80}${option.path || '/'}`;
       }
-      options.transportOptions = { ...options.transportOptions, ...option };
```
Comment (abmusse) [inline lib/Deprecated.js:568]: Looks like this change is the cause of [unit test failure](https://github.com/IBM/nodejs-itoolkit/pull/272/checks?check_run_id=630828052#step:6:273). We should still append user passed options to the transportOptions like we did before.

Comment (kadler) [reply lib/Deprecated.js:568]: Oops. I should have caught that.
