### PR TITLE
fix: Properly close stmt and conn when using idb

### LINKED ISSUE #230: Data queue memory leak itoolkit 0.1.6 + idb-connector
We're having issues in production similar to [this issue](https://github.com/IBM/nodejs-idb-connector/issues/90) raised in idb-connector a while ago.

We're seeing the temporary storage use on the node job increase rather fast when reading and writing to data queues. This doesn't happen when using the REST transport so I thought this may be an issue with idb-connector. On further testing, I've found the issue doesn't seem to occur with the newer alpha1 version of itoolkit in npm repos using the Toolkit class to read/write data queues so decided to raise it here instead.

Are you still supporting issues with the older version of itoolkit? If not, are there plans to implement reading/writing **keyed** data queues in the newer version soon™ ([it looks like Toolkit dataqueue stuff is being canned](https://github.com/IBM/nodejs-itoolkit/issues/97))?

Thanks.

### PR DESCRIPTION
**Pull request by kadler**
Deleting the statement object doesn't free the underlying resources,
causing memory leaks. Instead, we need to close both the connection and
the statement to free these resources. We can let the runtime delete the
objects as well.

Fixes #230

### CODE REVIEW

**Comment by kadler** [comment]
This might not be 100% correct for sync mode, since I don't know how errors are returned in that case (exceptions?)

**Comment by abmusse** [comment]
> This might not be 100% correct for sync mode, since I don't know how errors are returned in that case (exceptions?)

Yup sync mode will throw an error. [prepareSync](https://github.com/IBM/nodejs-itoolkit/pull/232/files#diff-abd3b678c25de8ba7988573f62013576R71) would throw an error [here](https://github.com/IBM/nodejs-idb-connector/blob/master/src/db2ia/dbstmt.cc#L655).

This won't give you the chance to properly close things out with `cleanup()`.

Looks we can get around this by passing a callback to [prepareSync](https://github.com/IBM/nodejs-idb-connector/blob/master/src/db2ia/dbstmt.cc#L660). That way we can check for an error just like the [async case](https://github.com/IBM/nodejs-itoolkit/pull/232/files#diff-abd3b678c25de8ba7988573f62013576R84)

File: lib/istoredp.js [hunk 1]
```diff
@@ -60,33 +60,45 @@ const db2Call = (callback,xlib,xdatabase,xuser,xpassword,xipc,xctl,xml_input_scr
...
       ];
+
+    const cleanup = () => {
+      stmt.close();
+      conn.disconn();
+      conn.close();
+    };
         
     if(sync == true) {  // Sync Mode
       stmt.prepareSync(sql);
```
Comment (abmusse) [inline lib/istoredp.js:71]: We should pass a callback to [prepareSync](https://github.com/IBM/nodejs-idb-connector/tree/master/docs#dbstmtpreparesyncsql--callback) and check for an error. Then run `cleanup()` if an error occured.

File: lib/istoredp.js [hunk 2]
```diff
@@ -60,33 +60,45 @@ const db2Call = (callback,xlib,xdatabase,xuser,xpassword,xipc,xctl,xml_input_scr
...
       stmt.bindParamSync(bindParams);
```
Comment (abmusse) [inline lib/istoredp.js:72]: We should pass a callback to [bindParamSync](https://github.com/IBM/nodejs-idb-connector/tree/master/docs#dbstmtbindparamsyncparams--callback-deprecated) and check for an error. Then run `cleanup()` if an error occurred.  Otherwise the connection and statement won't be cleaned up properly.

File: lib/istoredp.js (hunk 1 above)
Comment (kadler) [reply lib/istoredp.js:71]: I think wrapping with try/catch would be better.

Comment (abmusse) [reply lib/istoredp.js:71]: Yes that would make more sense!

**Comment by kadler** [comment]
I've changed the whole design. Since everything throws errors, wrap the whole thing in try/finally blocks. This way we don't eve need the function, since the clean up code only happens in one place. 

The only downfall with this design is that cleanup will not be done until _after_ the user's callback chain has returned to us.

**Comment by abmusse** [comment]
I tried running through the tests with:

```
$ npm test test/functional/commandsFunctional.js

    Uncaught Error: SQLSTATE=PAERR SQLCODE=8013 The SQL Statment handler is not initialized.
      at ../istoredp.js:77:16

```
I'm trying to figure out why.

**Comment by abmusse** [comment]
@kadler

The JavaScript `try…catch` mechanism cannot be used to intercept errors generated by asynchronous APIs.

See https://nodejs.org/api/errors.html#errors_error_first_callbacks

Running the command test with verbose mode on we can see:

```
============
INPUT XML
============
<?xml version='1.0'?><myscript><cmd exec='rexx' error='fast'>RTVJOBA USRLIBL(?) SYSLIBL(?)</cmd></myscript>
============
OUTPUT XML
============
SQLConnect(0): conn obj [1805037d0] handler [2]
creating statement
stmt is dbstmt {}
Prepare().
SQLFreeStmt: stmth 3 [SQL_DROP]
SQLFreeStmt(0)
SQLDisconnect: conn obj [1805037d0] handler [2]
SQLFreeConnect: conn obj [1805037d0] handler [2]
SQLFreeConnect[0]
SQLPrepare(-2): call QXMLSERV.iPLUG512K(?,?,?,?)
calling bind
BindParamAsync().
      1) calls CL command using idb transport


  0 passing (114ms)
  1 failing

  1) iSh, iCmd, iQsh, Functional Tests
       iCmd()
         calls CL command using idb transport:
     Uncaught Error: SQLSTATE=PAERR SQLCODE=8013 The SQL Statment handler is not initialized.
      at ../istoredp.js:83:16

```

Looks like the finally block runs before prepare finishes causing the statement handle to be invalid `SQLPrepare(-2)`.

**Comment by kadler** [comment]
Ugh, that makes sense. The fact that the whole thing is wrapped in an exception handler and the code throws is what lead me to that. Now I wonder if the code is currently broken.

**Comment by kadler** [comment]
I moved the try/finally around the sync mode block and in the async block I used the same way I had before.

File: lib/istoredp.js [hunk 3]
```diff
@@ -60,33 +60,50 @@ const db2Call = (callback,xlib,xdatabase,xuser,xpassword,xipc,xctl,xml_input_scr
...
-        else
-          callback(outArray);  // For multiple return result, caller should handle it as an array.
-        delete stmt;
-        conn.disconn();
-        delete conn;
-      });
+      try {
+        stmt.prepareSync(sql);
+        stmt.bindParamSync(bindParams);
+        stmt.executeSync((outArray) => {  //out is an array of the output parameters.
```
[the remark this answers is not in the document]
Comment (abmusse) [reply lib/istoredp.js:74]: [executeSync](https://github.com/IBM/nodejs-idb-connector/tree/master/docs#dbstmtexecutesynccallback) should return the `outArray` when called without the callback. 

```js
const outArray = executeSync();

if(outArray.length == 1)
    callback(outArray[0]); 
 else
     callback(outArray);

```

**Comment by kadler** [comment]
@abmusse can you please make a v1.0.7 release?

**Comment by abmusse** [comment]
I believe you meant `v0.1.7` right?

Also after making the release on github also push to npm?

**Comment by kadler** [comment]
Yep. Caught my mistake a hair too late.
